### ISSUE TITLE
data

### ISSUE THREAD

**Issue by liang007-a** [sauravjoshi23/Web-Scraping#1]
Could you give me some data samples？
                     Thanks！

**Comment by sauravjoshi23** [comment]
Hey, @liang007-a initially I couldn't find a text classification dataset where the training data is very less ( but there were image datasets though) hence I created the dataset manually by deleting rows from the original large dataframe.

**Comment by liang007-a** [comment]
thank you! 
I want to ask again, what is the meaning of the label, why are all marked 1, under what circumstances can change the value?

**Comment by sauravjoshi23** [comment]
That is specifically for identity loss but in my opinion has no effect on the end result.
